'use client';
import React from 'react';

export default function PrintShell({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ fontFamily: 'Inter, system-ui, sans-serif', fontSize: 12, color: '#111' }}>
      <header style={{ marginBottom: 16, borderBottom: '1px solid #ddd', paddingBottom: 8 }}>
        <h1 style={{ fontSize: 18, margin: 0 }}>{title}</h1>
        <div style={{ fontSize: 11, color: '#555' }}>{new Date().toLocaleString()}</div>
      </header>
      <main>{children}</main>
      <footer style={{ marginTop: 24, borderTop: '1px solid #eee', paddingTop: 8, fontSize: 10, color: '#666' }}>
        Generated by Business Lending Advocate • {new Date().getFullYear()}
      </footer>
    </div>
  );
}
