'use client';

import Link from 'next/link';
import { useMemo, useState } from 'react';
import {
  ArrowRight,
  Check,
  Download,
  Eye,
  FileCheck2,
  FileText,
  FolderOpen,
  Link2,
  Package,
  RotateCcw,
  ShieldCheck,
  Upload,
} from 'lucide-react';

type DemoSection = 'loan-profile' | 'documents' | 'cover-letter' | 'package';
type DemoDocumentStatus = 'approved' | 'generated' | 'uploaded' | 'not_started';

type DemoDocument = {
  id: string;
  name: string;
  detail: string;
  status: DemoDocumentStatus;
  template?: boolean;
};

const initialDocuments: DemoDocument[] = [
  { id: 'personal-financial', name: 'Personal Financial Statement', detail: 'SBA Form 413 for the guarantor', status: 'generated', template: true },
  { id: 'personal-debt', name: 'Personal Debt Summary', detail: 'Personal balances and monthly payments', status: 'not_started', template: true },
  { id: 'business-debt', name: 'Business Debt Summary', detail: 'Current business liabilities and payments', status: 'approved', template: true },
  { id: 'balance-sheet', name: 'Current Balance Sheet', detail: 'Assets, liabilities, and equity', status: 'generated', template: true },
  { id: 'income-statement', name: 'Income Statement — YTD', detail: 'Current revenue, expenses, and profit', status: 'not_started', template: true },
  { id: 'business-tax-1', name: 'Business Tax Return — Year 1', detail: 'Most recent completed tax year', status: 'uploaded' },
  { id: 'business-tax-2', name: 'Business Tax Return — Year 2', detail: 'Prior completed tax year', status: 'not_started' },
  { id: 'personal-tax-1', name: 'Personal Tax Return — Year 1', detail: 'Most recent guarantor return', status: 'uploaded' },
  { id: 'bank-statements', name: 'Business Bank Statements', detail: 'Most recent three months', status: 'not_started' },
  { id: 'equipment-quote', name: 'Equipment Quote', detail: 'Vendor quote supporting use of funds', status: 'not_started' },
];

const sectionMeta: Array<{ id: DemoSection; title: string; description: string }> = [
  { id: 'loan-profile', title: 'Loan Profile', description: 'Request details reused across the package' },
  { id: 'documents', title: 'Document Checklist', description: 'Upload files or complete guided templates' },
  { id: 'cover-letter', title: 'Lender Cover Letter', description: 'Explain the request and repayment story' },
  { id: 'package', title: 'Download & Share', description: 'Build the ZIP and secure lender link' },
];

const completeStatuses = new Set<DemoDocumentStatus>(['approved', 'generated', 'uploaded']);

export default function LoanPackagingDemo({ compact = false }: { compact?: boolean }) {
  const [activeSection, setActiveSection] = useState<DemoSection>('documents');
  const [businessName, setBusinessName] = useState('Mesa Verde Equipment Co.');
  const [loanPurpose, setLoanPurpose] = useState('Equipment Purchase');
  const [loanAmount, setLoanAmount] = useState('350,000');
  const [documents, setDocuments] = useState(initialDocuments);
  const [coverLetterApproved, setCoverLetterApproved] = useState(false);
  const [packageBuilt, setPackageBuilt] = useState(false);
  const [linkPreviewOpen, setLinkPreviewOpen] = useState(false);
  const [coverLetter, setCoverLetter] = useState('Mesa Verde Equipment Co. is requesting $350,000 to purchase two additional service vehicles and diagnostic equipment. The investment will expand field capacity and support existing customer demand. Repayment is expected from operating cash flow generated by the added service volume.');
  const [coverInputs, setCoverInputs] = useState({
    businessDescription: 'Commercial equipment repair and field service provider',
    industry: 'Industrial services',
    useOfFunds: 'Two service vehicles and diagnostic equipment',
    repaymentSource: 'Operating cash flow from expanded service capacity',
  });

  const completedDocuments = documents.filter((document) => completeStatuses.has(document.status)).length;
  const loanProfileComplete = Boolean(businessName.trim() && loanPurpose && loanAmount.trim());
  const documentsComplete = completedDocuments === documents.length;
  const progress = Math.round(
    (loanProfileComplete ? 25 : 0) +
      (completedDocuments / documents.length) * 50 +
      (coverLetterApproved ? 25 : 0),
  );

  const nextAction = !loanProfileComplete
    ? 'Finish the loan profile.'
    : !documentsComplete
      ? `Complete ${documents.length - completedDocuments} remaining documents.`
      : !coverLetterApproved
        ? 'Review and complete the lender cover letter.'
        : 'Build the package and create a lender link.';

  const resetDemo = () => {
    setActiveSection('documents');
    setBusinessName('Mesa Verde Equipment Co.');
    setLoanPurpose('Equipment Purchase');
    setLoanAmount('350,000');
    setDocuments(initialDocuments);
    setCoverLetterApproved(false);
    setPackageBuilt(false);
    setLinkPreviewOpen(false);
    setCoverLetter('Mesa Verde Equipment Co. is requesting $350,000 to purchase two additional service vehicles and diagnostic equipment. The investment will expand field capacity and support existing customer demand. Repayment is expected from operating cash flow generated by the added service volume.');
    setCoverInputs({
      businessDescription: 'Commercial equipment repair and field service provider',
      industry: 'Industrial services',
      useOfFunds: 'Two service vehicles and diagnostic equipment',
      repaymentSource: 'Operating cash flow from expanded service capacity',
    });
  };

  const completeDocument = (id: string, status: 'generated' | 'uploaded') => {
    setPackageBuilt(false);
    setLinkPreviewOpen(false);
    setDocuments((current) => current.map((document) => document.id === id ? { ...document, status } : document));
  };

  const toggleCoverLetterApproval = () => {
    setCoverLetterApproved((current) => !current);
    setPackageBuilt(false);
    setLinkPreviewOpen(false);
  };

  const updateCoverInput = (field: keyof typeof coverInputs, value: string) => {
    setCoverInputs((current) => ({ ...current, [field]: value }));
    setCoverLetterApproved(false);
  };

  const regenerateCoverLetter = () => {
    setCoverLetter(`${businessName || 'The business'} is a ${coverInputs.businessDescription.toLowerCase()} in the ${coverInputs.industry.toLowerCase()} industry requesting $${loanAmount || '350,000'} for ${coverInputs.useOfFunds.toLowerCase()}. The investment will expand operating capacity and support existing customer demand. Repayment is expected from ${coverInputs.repaymentSource.toLowerCase()}.`);
    setCoverLetterApproved(false);
  };

  const activeMeta = useMemo(
    () => sectionMeta.find((section) => section.id === activeSection) ?? sectionMeta[0]!,
    [activeSection],
  );

  return (
    <div className="overflow-hidden rounded-[1.4rem] border border-slate-200 bg-white shadow-[0_28px_80px_-46px_rgba(15,23,42,0.55)]">
      <div className="bg-gradient-to-r from-slate-950 via-slate-900 to-blue-950 px-4 py-4 text-white sm:px-5">
        <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <div className="flex flex-wrap items-center gap-2">
              <span className="inline-flex items-center gap-1.5 rounded-full border border-blue-300/30 bg-blue-300/10 px-2.5 py-1 text-[11px] font-bold uppercase tracking-[0.12em] text-blue-100">
                <ShieldCheck className="h-3.5 w-3.5" />Interactive sample
              </span>
              <span className="text-[11px] font-medium text-slate-400">Changes stay in this demo</span>
            </div>
            <p className="mt-2 text-base font-extrabold sm:text-lg">Small Business Loan Packaging</p>
          </div>
          <div className="flex items-center gap-3 rounded-xl border border-white/10 bg-white/[0.06] px-3 py-2">
            <div>
              <p className="text-[11px] font-bold uppercase tracking-[0.14em] text-slate-400">Package progress</p>
              <p className="text-xl font-black text-white">{progress}%</p>
            </div>
            <div className="h-9 w-9 rounded-full p-1" style={{ background: `conic-gradient(#34d399 ${progress * 3.6}deg, rgba(255,255,255,.12) 0deg)` }}>
              <div className="flex h-full w-full items-center justify-center rounded-full bg-slate-950"><Check className="h-3.5 w-3.5 text-emerald-300" /></div>
            </div>
          </div>
        </div>
      </div>

      <div className={`grid ${compact ? 'lg:grid-cols-[180px_minmax(0,1fr)]' : 'lg:grid-cols-[220px_minmax(0,1fr)]'}`}>
        <aside className="border-b border-slate-200 bg-slate-50/80 p-3 lg:border-b-0 lg:border-r lg:p-4">
          <p className="text-[11px] font-black uppercase tracking-[0.14em] text-slate-500">Workflow status</p>
          <div className="mt-2 grid grid-cols-2 gap-2 lg:mt-3 lg:block lg:space-y-2">
            {sectionMeta.map((section, index) => (
              <button key={section.id} type="button" onClick={() => setActiveSection(section.id)} className={`flex w-full items-center gap-2 rounded-lg px-2.5 py-2 text-left text-xs font-semibold transition ${activeSection === section.id ? 'bg-white text-slate-950 shadow-sm' : 'text-slate-600 hover:bg-white/70'}`}>
                <span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-slate-200 text-[11px]">{index + 1}</span>{section.title}
              </button>
            ))}
          </div>
          <div className="mt-3 rounded-xl border border-amber-200 bg-amber-50 p-3 lg:mt-4">
            <p className="text-[11px] font-black uppercase tracking-[0.12em] text-amber-800">Next action</p>
            <p className="mt-1.5 text-xs leading-5 text-amber-950">{nextAction}</p>
          </div>
        </aside>

        <div aria-live="polite" className={compact ? 'p-3 sm:p-4' : 'p-4 sm:p-6'}>
          <div className="flex items-start justify-between gap-3 border-b border-slate-100 pb-3">
            <div>
              <p className="text-sm font-extrabold text-slate-950">{activeMeta.title}</p>
              <p className="mt-0.5 text-xs text-slate-500">{activeMeta.description}</p>
            </div>
            <button type="button" onClick={resetDemo} className="inline-flex shrink-0 items-center gap-1.5 rounded-lg border border-slate-200 bg-white px-2.5 py-1.5 text-[11px] font-bold text-slate-600 transition hover:bg-slate-50"><RotateCcw className="h-3 w-3" />Reset</button>
          </div>

          {activeSection === 'loan-profile' ? (
            <div className="mt-4 grid gap-3 sm:grid-cols-3">
              <label className="text-xs font-bold text-slate-700">Business Name<input value={businessName} onChange={(event) => setBusinessName(event.target.value)} className="mt-1.5 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm font-medium outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100" /></label>
              <label className="text-xs font-bold text-slate-700">Loan Purpose<select value={loanPurpose} onChange={(event) => setLoanPurpose(event.target.value)} className="mt-1.5 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm font-medium outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100"><option>Equipment Purchase</option><option>Working Capital</option><option>Business Acquisition</option><option>Commercial Real Estate Purchase</option></select></label>
              <label className="text-xs font-bold text-slate-700">Loan Amount<div className="relative mt-1.5"><span className="absolute left-3 top-2 text-sm text-slate-500">$</span><input value={loanAmount} onChange={(event) => setLoanAmount(event.target.value)} className="w-full rounded-lg border border-slate-300 py-2 pl-7 pr-3 text-sm font-medium outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100" /></div></label>
              <div className="rounded-xl border border-blue-100 bg-blue-50 p-3 sm:col-span-3"><p className="text-[11px] font-black uppercase tracking-[0.12em] text-blue-700">Use of funds</p><div className="mt-2 grid gap-2 sm:grid-cols-3"><div className="rounded-lg bg-white px-3 py-2 text-xs font-semibold text-slate-700">Service vehicles <span className="float-right">$240,000</span></div><div className="rounded-lg bg-white px-3 py-2 text-xs font-semibold text-slate-700">Diagnostic equipment <span className="float-right">$85,000</span></div><div className="rounded-lg bg-white px-3 py-2 text-xs font-semibold text-slate-700">Working capital <span className="float-right">$25,000</span></div></div></div>
            </div>
          ) : null}

          {activeSection === 'documents' ? (
            <div className="mt-4">
              <div className="mb-3 flex flex-wrap items-center justify-between gap-2"><p className="text-xs font-semibold text-slate-600">{completedDocuments} of {documents.length} required documents complete</p><div className="h-1.5 w-36 overflow-hidden rounded-full bg-slate-200"><div className="h-full rounded-full bg-emerald-500 transition-all" style={{ width: `${(completedDocuments / documents.length) * 100}%` }} /></div></div>
              <div className={`grid gap-2 ${compact ? 'md:grid-cols-2' : 'xl:grid-cols-2'}`}>
                {documents.map((document) => (
                  <div key={document.id} className={`flex items-center justify-between gap-3 rounded-xl border p-3 transition hover:shadow-sm ${completeStatuses.has(document.status) ? 'border-emerald-300 bg-emerald-100/80' : 'border-slate-200 bg-white hover:border-blue-300'}`}>
                    <div className="flex min-w-0 items-start gap-2.5"><span className={`mt-0.5 flex h-8 w-8 shrink-0 items-center justify-center rounded-lg ${completeStatuses.has(document.status) ? 'bg-emerald-600 text-white' : document.template ? 'bg-indigo-50 text-indigo-700' : 'bg-blue-50 text-blue-700'}`}>{completeStatuses.has(document.status) ? <Check className="h-4 w-4" /> : document.template ? <FileText className="h-4 w-4" /> : <Upload className="h-4 w-4" />}</span><span className="min-w-0"><span className="block truncate text-xs font-extrabold text-slate-900">{document.name}</span><span className="mt-0.5 block truncate text-[11px] text-slate-500">{document.detail}</span></span></div>
                    {completeStatuses.has(document.status) ? <span className="inline-flex shrink-0 items-center gap-1 rounded-full bg-emerald-700 px-2.5 py-1.5 text-[11px] font-bold text-white"><Check className="h-3 w-3" />Submitted</span> : <div className="flex shrink-0 gap-1.5"><button type="button" onClick={() => completeDocument(document.id, 'uploaded')} className="inline-flex items-center gap-1 rounded-lg border border-blue-300 bg-blue-50 px-2 py-1.5 text-[11px] font-bold text-blue-700 transition hover:bg-blue-100"><Upload className="h-3 w-3" />Upload</button>{document.template ? <button type="button" onClick={() => completeDocument(document.id, 'generated')} className="inline-flex items-center gap-1 rounded-lg border border-emerald-300 bg-emerald-50 px-2 py-1.5 text-[11px] font-bold text-emerald-700 transition hover:bg-emerald-100"><FileText className="h-3 w-3" />Use template</button> : null}</div>}
                  </div>
                ))}
              </div>
              <p className="mt-3 text-[11px] leading-4 text-slate-500">Use the sample Upload or Use template actions to submit unfinished items. Real files are available only in your secure workspace.</p>
            </div>
          ) : null}

          {activeSection === 'cover-letter' ? (
            <div className="mt-4">
              <div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{['Business Overview', 'Use of Funds', 'Repayment', 'Review'].map((tab, index) => <div key={tab} className={`flex items-center gap-2 rounded-lg border px-3 py-2 text-xs font-bold ${index < 3 ? 'border-emerald-200 bg-emerald-50 text-emerald-800' : 'border-slate-200 bg-slate-50 text-slate-600'}`}><span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-white">{index < 3 ? <Check className="h-3 w-3" /> : 4}</span>{tab}</div>)}</div>
              <div className="mt-3 grid gap-3 lg:grid-cols-[0.88fr_1.12fr]">
                <div className="rounded-xl border border-slate-200 bg-slate-50 p-3">
                  <p className="text-xs font-extrabold text-slate-950">Sample inputs used to generate the draft</p>
                  <div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-1">
                    <label className="text-[11px] font-bold text-slate-600">What does the business do?<input value={coverInputs.businessDescription} onChange={(event) => updateCoverInput('businessDescription', event.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 bg-white px-2.5 py-2 text-xs text-slate-800 outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100" /></label>
                    <label className="text-[11px] font-bold text-slate-600">Industry<input value={coverInputs.industry} onChange={(event) => updateCoverInput('industry', event.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 bg-white px-2.5 py-2 text-xs text-slate-800 outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100" /></label>
                    <label className="text-[11px] font-bold text-slate-600">How will the funds be used?<input value={coverInputs.useOfFunds} onChange={(event) => updateCoverInput('useOfFunds', event.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 bg-white px-2.5 py-2 text-xs text-slate-800 outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100" /></label>
                    <label className="text-[11px] font-bold text-slate-600">Primary repayment source<input value={coverInputs.repaymentSource} onChange={(event) => updateCoverInput('repaymentSource', event.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 bg-white px-2.5 py-2 text-xs text-slate-800 outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100" /></label>
                  </div>
                  <button type="button" onClick={regenerateCoverLetter} className="mt-3 inline-flex items-center gap-2 rounded-lg border border-blue-200 bg-blue-50 px-3 py-2 text-xs font-bold text-blue-800 transition hover:bg-blue-100"><FileText className="h-3.5 w-3.5" />Regenerate sample draft</button>
                </div>
                <div><label className="text-xs font-bold text-slate-700">Editable lender-facing draft<textarea value={coverLetter} onChange={(event) => { setCoverLetter(event.target.value); setCoverLetterApproved(false); }} rows={compact ? 11 : 13} className="mt-1.5 w-full rounded-xl border border-slate-300 p-3 text-xs leading-5 text-slate-700 outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100" /></label><button type="button" onClick={toggleCoverLetterApproval} className={`mt-2 inline-flex items-center gap-2 rounded-lg px-3 py-2 text-xs font-bold transition ${coverLetterApproved ? 'bg-emerald-100 text-emerald-800' : 'bg-slate-900 text-white hover:bg-slate-800'}`}><FileCheck2 className="h-3.5 w-3.5" />{coverLetterApproved ? 'Complete and saved as PDF' : 'Complete sample cover letter'}</button></div>
              </div>
            </div>
          ) : null}

          {activeSection === 'package' ? (
            <div className="mt-4 grid gap-3 sm:grid-cols-2">
              <div className={`rounded-xl border p-4 ${progress === 100 ? 'border-emerald-200 bg-emerald-50' : 'border-amber-200 bg-amber-50'}`}><Package className={`h-5 w-5 ${progress === 100 ? 'text-emerald-700' : 'text-amber-800'}`} /><p className="mt-3 text-sm font-extrabold text-slate-950">Build & Download ZIP</p><p className="mt-1 text-xs leading-5 text-slate-600">Combines the approved cover letter and completed documents into one organized package.</p><button type="button" disabled={progress < 100} onClick={() => setPackageBuilt(true)} className="mt-3 inline-flex items-center gap-2 rounded-lg bg-slate-900 px-3 py-2 text-xs font-bold text-white disabled:cursor-not-allowed disabled:opacity-40"><Download className="h-3.5 w-3.5" />{packageBuilt ? 'Sample ZIP prepared' : 'Build sample package'}</button></div>
              <div className="rounded-xl border border-slate-200 bg-slate-50 p-4"><Link2 className="h-5 w-5 text-blue-700" /><p className="mt-3 text-sm font-extrabold text-slate-950">Create Secure Lender Link</p><p className="mt-1 text-xs leading-5 text-slate-600">Share a controlled lender portal with an expiration date instead of emailing loose attachments.</p><button type="button" disabled={progress < 100} onClick={() => setLinkPreviewOpen((current) => !current)} className="mt-3 inline-flex items-center gap-2 rounded-lg border border-slate-300 bg-white px-3 py-2 text-xs font-bold text-slate-700 disabled:cursor-not-allowed disabled:opacity-40"><Eye className="h-3.5 w-3.5" />{linkPreviewOpen ? 'Hide sample link' : 'Preview sample link'}</button></div>
              {progress < 100 ? <div className="rounded-xl border border-blue-200 bg-blue-50 p-3 text-xs leading-5 text-blue-900 sm:col-span-2"><strong>Demo next step:</strong> finish the document checklist and approve the cover letter to unlock package delivery.</div> : null}
              {packageBuilt ? <div className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-xs leading-5 text-emerald-900 sm:col-span-2"><strong>Sample package prepared:</strong> Mesa-Verde-Equipment-Co-Loan-Package.zip • 12 organized files • no file was actually created or downloaded.</div> : null}
              {linkPreviewOpen ? <div className="rounded-xl border border-indigo-200 bg-indigo-50 p-3 text-xs leading-5 text-indigo-900 sm:col-span-2"><strong>Sample lender portal:</strong> Mesa Verde Equipment Co. • password protected • expires in 14 days • view-only access.</div> : null}
            </div>
          ) : null}
        </div>
      </div>

      <div className="flex flex-col gap-2 border-t border-slate-200 bg-slate-50 px-4 py-3 sm:flex-row sm:items-center sm:justify-between">
        <p className="flex items-center gap-2 text-[11px] font-medium text-slate-500"><FolderOpen className="h-3.5 w-3.5" />Sample borrower data only. Nothing is uploaded or saved.</p>
        {compact ? <Link href="/loan-packaging-demo" className="group inline-flex items-center gap-1.5 text-xs font-extrabold text-blue-800">Open full interactive demo <ArrowRight className="h-3.5 w-3.5 transition group-hover:translate-x-1" /></Link> : <Link href="/loan-services" className="group inline-flex items-center gap-2 rounded-lg bg-slate-900 px-4 py-2 text-xs font-bold text-white">Build your real loan package <ArrowRight className="h-3.5 w-3.5 transition group-hover:translate-x-1" /></Link>}
      </div>
    </div>
  );
}
