import type {
  BalanceSheetData,
  BusinessDebtSummaryData,
  IncomeStatementData,
  PersonalDebtSummaryData,
  PersonalFinancialStatementData,
} from '@/lib/templates/types';

export const incomeStatementPreviewData: IncomeStatementData = {
  statementLabel: 'FY 2025 Year-End',
  statementType: 'annual',
  periodStart: '2025-01-01',
  periodEnd: '2025-12-31',
  businessInfo: {
    name: 'Summit Ridge Contracting LLC',
  },
  revenue: {
    grossSales: 2280000,
    serviceRevenue: 340000,
    otherRevenue: 26500,
  },
  cogs: {
    inventoryMaterialsCost: 1185000,
    directLabor: 82000,
    shippingPackaging: 26000,
    otherDirectCosts: 17000,
  },
  operatingExpenses: {
    payrollContractorPayments: 420000,
    rentFacilityCosts: 98000,
    utilitiesInternet: 27500,
    marketingAdvertising: 46000,
    softwareSubscriptions: 18800,
    professionalServices: 24400,
    insurance: 38800,
    officeAdministrative: 22100,
    vehicleTravel: 29800,
    otherOperatingExpenses: 41200,
  },
  interestExpense: 41800,
  notes: '',
};

export const balanceSheetPreviewData: BalanceSheetData = {
  statementLabel: 'FY 2025 Year-End',
  statementType: 'year_end',
  asOfDate: '2025-12-31',
  businessInfo: {
    legalName: 'Summit Ridge Contracting LLC',
    reportBasis: 'accrual',
  },
  assets: {
    cashAndCashEquivalents: 118400,
    accountsReceivable: 94200,
    inventory: 48200,
    prepaidExpenses: 10600,
    otherCurrentAssets: 7800,
    fixedAssetBreakdown: {
      businessRealEstate: 465000,
      vehicles: 162000,
      machineryEquipment: 238000,
      furnitureFixtures: 43000,
      leaseholdImprovements: 28000,
    },
    accumulatedDepreciation: 192000,
    notesReceivable: 22000,
    intangibleAssets: 9000,
    investments: 54000,
    otherNonCurrentAssets: 12500,
  },
  liabilities: {
    accountsPayable: 77200,
    accruedExpenses: 28600,
    taxesPayable: 12400,
    currentPortionLongTermDebt: 35800,
    creditCardsAndLines: 46200,
    deferredRevenue: 14000,
    otherCurrentLiabilities: 9800,
    longTermDebt: 392000,
    shareholderLoans: 64000,
    otherLongTermLiabilities: 21200,
  },
  equity: {
    ownerContributions: 310000,
    retainedEarnings: 196900,
    ownerDistributions: 126500,
    otherEquity: 15000,
  },
  notes: '',
};

export const businessDebtSummaryPreviewData: BusinessDebtSummaryData = {
  asOfDate: '2026-03-01',
  businessInfo: {
    name: 'Harbor Ridge Logistics LLC',
    ein: '84-9123456',
    address: '5824 W Commerce St, San Antonio, TX 78237',
  },
  debts: [
    {
      category: 'credit_cards',
      creditor: 'Amex Business Gold - Operations',
      originalAmount: 0,
      currentBalance: 18640,
      monthlyPayment: 720,
      creditLimit: 30000,
      personalGuarantee: true,
    },
    {
      category: 'credit_cards',
      creditor: 'Chase Ink Business Preferred',
      originalAmount: 0,
      currentBalance: 11180,
      monthlyPayment: 420,
      creditLimit: 25000,
      personalGuarantee: true,
    },
    {
      category: 'line_of_credit',
      creditor: 'Regional Bank Operating LOC',
      originalAmount: 60000,
      currentBalance: 24850,
      monthlyPayment: 980,
      creditLimit: 60000,
      personalGuarantee: true,
    },
    {
      category: 'real_estate',
      creditor: 'Warehouse Mortgage - First Capital',
      originalAmount: 730000,
      currentBalance: 621500,
      monthlyPayment: 5340,
      personalGuarantee: false,
    },
    {
      category: 'vehicle_equipment',
      creditor: 'Fleet Vehicle Loan - 2024 Freightliner',
      originalAmount: 96500,
      currentBalance: 82400,
      monthlyPayment: 1690,
      personalGuarantee: false,
    },
    {
      category: 'term_loans',
      creditor: 'Working Capital Loan - Growth Fund',
      originalAmount: 150000,
      currentBalance: 103800,
      monthlyPayment: 2890,
      personalGuarantee: true,
    },
    {
      category: 'other_debt',
      creditor: 'State Tax Payment Plan',
      originalAmount: 28000,
      currentBalance: 17200,
      monthlyPayment: 760,
      personalGuarantee: false,
    },
  ],
  notes:
    'Demo dataset for visualization only. Actual output updates automatically based on submitted debt inputs.',
};

export const personalDebtSummaryPreviewData: PersonalDebtSummaryData = {
  asOfDate: '2026-03-01',
  personalInfo: {
    name: 'Jordan Rivera',
  },
  debts: [
    {
      category: 'credit_cards',
      creditor: 'Chase Sapphire Preferred',
      originalAmount: 0,
      currentBalance: 9200,
      monthlyPayment: 310,
      creditLimit: 17000,
    },
    {
      category: 'credit_cards',
      creditor: 'Amex Everyday',
      originalAmount: 0,
      currentBalance: 3800,
      monthlyPayment: 140,
      creditLimit: 9000,
    },
    {
      category: 'line_of_credit',
      creditor: 'Personal LOC - First National',
      originalAmount: 15000,
      currentBalance: 7200,
      monthlyPayment: 240,
      creditLimit: 15000,
    },
    {
      category: 'real_estate',
      creditor: 'Primary Residence Mortgage - Rocket',
      originalAmount: 385000,
      currentBalance: 346000,
      monthlyPayment: 2590,
    },
    {
      category: 'student_debt',
      creditor: 'Federal Student Loan - Nelnet',
      originalAmount: 36000,
      currentBalance: 24800,
      monthlyPayment: 330,
    },
    {
      category: 'vehicle',
      creditor: '2023 Toyota Highlander Loan',
      originalAmount: 42000,
      currentBalance: 31800,
      monthlyPayment: 690,
    },
    {
      category: 'other_debt',
      creditor: 'Personal Loan - SoFi',
      originalAmount: 22000,
      currentBalance: 13100,
      monthlyPayment: 430,
    },
  ],
  notes:
    'Demo dataset for visualization only. Actual output updates automatically based on submitted debt inputs.',
};

export const personalFinancialStatementPreviewData: PersonalFinancialStatementData = {
  asOfDate: '2026-03-01',
  personalInfo: {
    name: 'Jordan Rivera',
    address: '1824 Cedar Bluff Dr, San Antonio, TX 78258',
    homeStreet: '1824 Cedar Bluff Dr',
    homeCity: 'San Antonio',
    homeState: 'TX',
    homeZip: '78258',
    primaryPhone: '(210) 555-3984',
    phone: '(210) 555-3984',
    email: 'jordan.rivera@example.com',
  },
  businessInfo: {
    applicantBusinessName: 'Rivera Industrial Services LLC',
    applicantBusinessPhone: '(210) 555-3984',
    businessType: 'llc',
    businessStreet: '7218 Industrial Park Blvd',
    businessCity: 'San Antonio',
    businessState: 'TX',
    businessZip: '78249',
  },
  declarations: {
    isMarried: 'yes',
    isUsCitizen: 'yes',
    hasContingentLiability: 'yes',
    contingencyNotes: 'Personal guaranty on operating line of credit and one equipment lease.',
    hasLawsuitOrJudgment: 'no',
    hasTaxDelinquency: 'no',
    hasGuarantees: 'yes',
    guaranteesNotes: 'Personal guaranty on operating line of credit.',
  },
  assets: {
    cashChecking: 45200,
    cashSavings: 38800,
    accountsNotesReceivable: 12000,
    lifeInsuranceCashSurrender: 18500,
    stocksBonds: 74200,
    realEstate: 623000,
    automobiles: 61500,
    personalProperty: 27000,
    otherAssets: 16000,
  },
  liabilities: {
    creditCards: 18400,
    mortgages: 371000,
    autoLoans: 35600,
    studentLoans: 19800,
    otherDebts: 32900,
  },
  liabilityDetails: {
    creditCards: {
      hasBalances: 'yes',
      totalBalance: 18400,
      totalMonthlyPayment: 620,
    },
    medicalBills: {
      hasDebts: 'yes',
      totalBalance: 2400,
    },
    studentLoans: {
      hasLoans: 'yes',
      totalBalance: 19800,
      totalMonthlyPayment: 330,
    },
    hasPersonalLoans: 'yes',
    personalLoans: [
      {
        loanType: 'line_of_credit',
        lenderName: 'First National Bank',
        originalBalance: 25000,
        currentBalance: 13700,
        monthlyPayment: 390,
        isSecured: 'no',
      },
      {
        loanType: 'business_loan_pg',
        lenderName: 'Growth Fund Capital',
        originalBalance: 85000,
        currentBalance: 14200,
        monthlyPayment: 540,
        isSecured: 'yes',
        collateralType: 'business_assets',
        collateralDescription: 'business equipment and receivables',
      },
    ],
    hasTaxesOwed: 'yes',
    taxesOwed: [
      {
        authority: 'IRS Installment Agreement',
        originalBalance: 9800,
        balanceOwed: 6400,
        monthlyPayment: 225,
      },
      {
        authority: 'Texas Comptroller',
        originalBalance: 2100,
        balanceOwed: 1500,
        monthlyPayment: 95,
      },
    ],
    hasOtherObligations: 'yes',
    otherObligations: [
      {
        description: 'Family support obligation',
        amountOwed: 3600,
        monthlyPayment: 300,
      },
      {
        description: 'Private fitness studio membership contract',
        amountOwed: 1200,
        monthlyPayment: 100,
      },
    ],
  },
  contingentLiabilities: {
    asEndorserOrCoMaker: {
      hasExposure: 'yes',
      estimatedAmount: 18000,
    },
    legalClaimsAndJudgments: {
      hasExposure: 'no',
      estimatedAmount: 0,
    },
    provisionForFederalIncomeTax: {
      hasExposure: 'no',
      estimatedAmount: 0,
    },
    otherSpecialDebt: {
      hasExposure: 'yes',
      estimatedAmount: 9500,
    },
  },
  incomeDetails: {
    employmentIncome: {
      hasIncome: 'yes',
      averageGrossMonthlyIncome: 12333,
    },
    rentalIncome: {
      hasIncome: 'yes',
      averageNetMonthlyIncome: 1400,
    },
    investmentIncome: {
      hasIncome: 'yes',
      averageNetMonthlyIncome: 767,
    },
    otherIncome: {
      hasIncome: 'yes',
      averageMonthlyIncome: 350,
      description: 'Board advisory stipend',
      sources: [
        {
          sourceType: 'consulting',
          description: 'Board advisory stipend',
          averageMonthlyAmount: 350,
        },
      ],
    },
  },
  annualIncome: {
    salary: 148000,
    netInvestmentIncome: 9200,
    realEstateIncome: 16800,
    otherIncome: 4200,
    incomeContingencies: 'Income includes salary, net distributions, and rental cash flow.',
  },
  realEstateOwned: [
    {
      propertyType: 'primary_residence',
      propertyAddress: '1824 Cedar Bluff Dr, San Antonio, TX 78258',
      datePurchased: '2019-05-15',
      originalCost: 392000,
      presentMarketValue: 465000,
      mortgageHolderName: 'First National Mortgage',
      mortgageHolderAddress: 'PO Box 1189, Dallas, TX 75221',
      mortgageAccountNumber: 'FNM-443812',
      mortgageBalance: 286000,
      amountOfPaymentPerMonth: 2590,
      status: 'current',
    },
    {
      propertyType: 'rental_property',
      propertyAddress: '4302 Oak Ranch Ln, New Braunfels, TX 78132',
      datePurchased: '2021-08-01',
      originalCost: 144000,
      presentMarketValue: 158000,
      mortgageHolderName: 'Lone Star Community Bank',
      mortgageHolderAddress: '105 Main Plaza, New Braunfels, TX 78130',
      mortgageAccountNumber: 'LSB-220491',
      mortgageBalance: 85000,
      amountOfPaymentPerMonth: 970,
      status: 'current',
    },
  ],
  stocksAndBonds: [
    {
      symbol: 'VTI',
      issuerName: 'Vanguard Total Stock Market ETF',
      numberOfShares: 280,
      cost: 61250,
      marketValue: 265,
      dateOfQuote: '2026-03-01',
      exchange: 'NYSE Arca',
    },
    {
      symbol: 'BND',
      issuerName: 'Vanguard Total Bond Market ETF',
      numberOfShares: 110,
      cost: 7600,
      marketValue: 84,
      dateOfQuote: '2026-03-01',
      exchange: 'NASDAQ',
    },
  ],
  otherPersonalPropertyAndOtherAssets: [
    {
      description: 'Jewelry and watches',
      value: 9000,
    },
    {
      description: 'Home furnishings and electronics',
      value: 18000,
    },
  ],
  retirementAccounts: [
    {
      accountType: '401k',
      institutionName: 'Fidelity',
      currentEstimatedValue: 126000,
      pledgedAsCollateral: 'no',
    },
    {
      accountType: 'roth_ira',
      institutionName: 'Charles Schwab',
      currentEstimatedValue: 28500,
      pledgedAsCollateral: 'no',
    },
  ],
  vehiclesOwned: [
    {
      year: 2023,
      make: 'Toyota',
      model: 'Highlander',
      currentEstimatedValue: 42000,
      loanBalance: 24500,
      monthlyPayment: 690,
    },
    {
      year: 2022,
      make: 'Ford',
      model: 'F-150',
      currentEstimatedValue: 19500,
      loanBalance: 11100,
      monthlyPayment: 410,
    },
  ],
  accountsAndNotesReceivable: [
    {
      debtorName: 'Riverwalk Fabrication LLC',
      originalAmountLoaned: 18000,
      currentBalanceOwed: 12000,
      monthlyPaymentReceived: 650,
      hasWrittenAgreement: 'yes',
      isSecuredByCollateral: 'no',
    },
  ],
  notesPayableToBanksAndOthers: [
    {
      nameAndAddressOfNoteholder: 'First National Bank, 200 W Commerce St, San Antonio, TX 78205',
      originalBalance: 25000,
      currentBalance: 13700,
      paymentAmount: 390,
      frequency: 'Monthly',
      howSecuredOrEndorsed: 'Unsecured personal line of credit',
    },
    {
      nameAndAddressOfNoteholder: 'Growth Fund Capital, 1100 Broadway, San Antonio, TX 78215',
      originalBalance: 85000,
      currentBalance: 14200,
      paymentAmount: 540,
      frequency: 'Monthly',
      howSecuredOrEndorsed: 'Personally guaranteed business term loan secured by equipment',
    },
    {
      nameAndAddressOfNoteholder: 'Toyota Financial Services, PO Box 9490, Cedar Rapids, IA 52409',
      originalBalance: 42000,
      currentBalance: 24500,
      paymentAmount: 690,
      frequency: 'Monthly',
      howSecuredOrEndorsed: 'Secured by 2023 Toyota Highlander',
    },
  ],
  lifeInsuranceHeld: [
    {
      companyName: 'Northwestern Mutual',
      faceAmount: 500000,
      cashSurrenderValue: 18500,
      loanAgainstPolicy: 0,
      beneficiaries: 'Spouse and two children',
    },
  ],
  eSignature: {
    fullName: 'Jordan Rivera',
    signedAt: '2026-03-01',
  },
  notes: '',
};
