/** lib/templates/validate.ts */

import { z } from 'zod';

export const BalanceSheetSchema = z.object({
  statementLabel: z.string().max(80).optional(),
  statementType: z.enum(['year_end', 'ytd', 'interim', 'custom']).optional(),
  periodStartDate: z.string().optional(),
  periodEndDate: z.string().optional(),
  asOfDate: z.string().min(1, "As of date is required"),
  businessInfo: z.object({
    legalName: z.string().min(1, "Business legal name is required"),
    reportBasis: z.enum(['accrual', 'cash', 'tax', 'other']).optional(),
    reportBasisOther: z.string().max(80).optional(),
  }),
  assets: z.object({
    cashAndCashEquivalents: z.number().nonnegative().optional(),
    accountsReceivable: z.number().nonnegative().optional(),
    inventory: z.number().nonnegative().optional(),
    prepaidExpenses: z.number().nonnegative().optional(),
    otherCurrentAssets: z.number().nonnegative().optional(),
    fixedAssetBreakdown: z.object({
      businessRealEstate: z.number().nonnegative().optional(),
      vehicles: z.number().nonnegative().optional(),
      machineryEquipment: z.number().nonnegative().optional(),
      furnitureFixtures: z.number().nonnegative().optional(),
      leaseholdImprovements: z.number().nonnegative().optional(),
    }).optional(),
    grossFixedAssets: z.number().nonnegative().optional(),
    accumulatedDepreciation: z.number().nonnegative().optional(),
    notesReceivable: z.number().nonnegative().optional(),
    intangibleAssets: z.number().nonnegative().optional(),
    investments: z.number().nonnegative().optional(),
    otherNonCurrentAssets: z.number().nonnegative().optional(),
  }),
  liabilities: z.object({
    accountsPayable: z.number().nonnegative().optional(),
    accruedExpenses: z.number().nonnegative().optional(),
    taxesPayable: z.number().nonnegative().optional(),
    currentPortionLongTermDebt: z.number().nonnegative().optional(),
    creditCardsAndLines: z.number().nonnegative().optional(),
    deferredRevenue: z.number().nonnegative().optional(),
    otherCurrentLiabilities: z.number().nonnegative().optional(),
    longTermDebt: z.number().nonnegative().optional(),
    shareholderLoans: z.number().nonnegative().optional(),
    otherLongTermLiabilities: z.number().nonnegative().optional(),
  }),
  equity: z.object({
    ownerContributions: z.number().optional(),
    retainedEarnings: z.number().optional(),
    ownerDistributions: z.number().nonnegative().optional(),
    otherEquity: z.number().optional(),
  }),
  notes: z.string().optional(),
});

export const IncomeStatementSchema = z.object({
  statementLabel: z.string().max(80).optional(),
  statementType: z.enum(['annual', 'ytd', 'quarterly', 'custom']).optional(),
  periodStart: z.string().min(1, "Period start date is required"),
  periodEnd: z.string().min(1, "Period end date is required"),
  businessInfo: z.object({
    name: z.string().max(180).optional(),
  }).optional(),
  revenue: z.object({
    grossSales: z.number().nonnegative().optional(),
    serviceRevenue: z.number().nonnegative().optional(),
    otherRevenue: z.number().nonnegative().optional(),
  }),
  cogs: z.object({
    inventoryMaterialsCost: z.number().nonnegative().optional(),
    directLabor: z.number().nonnegative().optional(),
    shippingPackaging: z.number().nonnegative().optional(),
    otherDirectCosts: z.number().nonnegative().optional(),
  }).optional(),
  operatingExpenses: z.object({
    payrollContractorPayments: z.number().nonnegative().optional(),
    rentFacilityCosts: z.number().nonnegative().optional(),
    utilitiesInternet: z.number().nonnegative().optional(),
    marketingAdvertising: z.number().nonnegative().optional(),
    softwareSubscriptions: z.number().nonnegative().optional(),
    professionalServices: z.number().nonnegative().optional(),
    insurance: z.number().nonnegative().optional(),
    officeAdministrative: z.number().nonnegative().optional(),
    vehicleTravel: z.number().nonnegative().optional(),
    otherOperatingExpenses: z.number().nonnegative().optional(),
  }).optional(),
  interestExpense: z.number().nonnegative().optional(),
  expenses: z.object({
    costOfGoodsSold: z.number().nonnegative().optional(),
    salariesWages: z.number().nonnegative().optional(),
    rent: z.number().nonnegative().optional(),
    utilities: z.number().nonnegative().optional(),
    marketing: z.number().nonnegative().optional(),
    insurance: z.number().nonnegative().optional(),
    depreciation: z.number().nonnegative().optional(),
    interestExpense: z.number().nonnegative().optional(),
    otherExpenses: z.number().nonnegative().optional(),
  }).optional(),
  notes: z.string().optional(),
});

export const PersonalFinancialStatementSchema = z.object({
  asOfDate: z.string().min(1, "As of date is required"),
  progressState: z.object({
    hasAccountsAndNotesReceivable: z.enum(['yes', 'no']).optional(),
    hasRetirementAccounts: z.enum(['yes', 'no']).optional(),
    hasLifeInsuranceCashValue: z.enum(['yes', 'no']).optional(),
    hasStocksAndBonds: z.enum(['yes', 'no']).optional(),
    realEstateCountChosen: z.boolean().optional(),
    vehicleCountChosen: z.boolean().optional(),
  }).optional(),
  personalInfo: z.object({
    name: z.string().min(2, "Name must be at least 2 characters").max(100, "Name must be 100 characters or fewer"),
    address: z.string().optional(),
    homeStreet: z.string().max(120, "Street must be 120 characters or fewer").optional(),
    homeCity: z.string().max(80, "City must be 80 characters or fewer").optional(),
    homeState: z.string().length(2, "Use 2-letter state code").optional(),
    homeZip: z.string().regex(/^\d{5}(-\d{4})?$/, "ZIP must be 5 digits or ZIP+4").optional(),
    primaryPhone: z.string().regex(/^[0-9+()\-.\s]{10,20}$/, "Phone must be 10-20 valid characters").optional(),
    phone: z.string().optional(),
    email: z.string().email("Enter a valid email").max(254, "Email must be 254 characters or fewer").optional().or(z.literal("")),
  }),
  coApplicant: z.object({
    name: z.string().optional(),
    address: z.string().optional(),
  }).optional(),
  businessInfo: z.object({
    applicantBusinessName: z.string().max(120, "Business name must be 120 characters or fewer").optional(),
    businessType: z.enum(['sole_proprietor', 'llc', 'corporation', 's_corp', 'partnership']).optional(),
    applicantBusinessPhone: z.string().regex(/^[0-9+()\-.\s]{10,20}$/, "Phone must be 10-20 valid characters").optional().or(z.literal("")),
    businessAddressDifferentFromHome: z.boolean().optional(),
    businessStreet: z.string().max(120, "Street must be 120 characters or fewer").optional(),
    businessCity: z.string().max(80, "City must be 80 characters or fewer").optional(),
    businessState: z.string().length(2, "Use 2-letter state code").optional(),
    businessZip: z.string().regex(/^\d{5}(-\d{4})?$/, "ZIP must be 5 digits or ZIP+4").optional(),
  }).optional(),
  declarations: z.object({
    isMarried: z.enum(['yes', 'no']).optional(),
    isUsCitizen: z.enum(['yes', 'no']).optional(),
    hasContingentLiability: z.enum(['yes', 'no']).optional(),
    contingencyNotes: z.string().optional(),
    hasLawsuitOrJudgment: z.enum(['yes', 'no']).optional(),
    lawsuitNotes: z.string().optional(),
    hasTaxDelinquency: z.enum(['yes', 'no']).optional(),
    taxNotes: z.string().optional(),
    hasGuarantees: z.enum(['yes', 'no']).optional(),
    guaranteesNotes: z.string().optional(),
  }).optional(),
  assets: z.object({
    cashChecking: z.number().nonnegative().optional(),
    cashSavings: z.number().nonnegative().optional(),
    accountsNotesReceivable: z.number().nonnegative().optional(),
    lifeInsuranceCashSurrender: z.number().nonnegative().optional(),
    stocksBonds: z.number().nonnegative().optional(),
    realEstate: z.number().nonnegative().optional(),
    automobiles: z.number().nonnegative().optional(),
    personalProperty: z.number().nonnegative().optional(),
    otherAssets: z.number().nonnegative().optional(),
  }),
  liabilities: z.object({
    creditCards: z.number().nonnegative().optional(),
    mortgages: z.number().nonnegative().optional(),
    autoLoans: z.number().nonnegative().optional(),
    studentLoans: z.number().nonnegative().optional(),
    otherDebts: z.number().nonnegative().optional(),
  }),
  liabilityDetails: z.object({
    creditCards: z.object({
      hasBalances: z.enum(['yes', 'no']).optional(),
      totalBalance: z.number().nonnegative().optional(),
      totalMonthlyPayment: z.number().nonnegative().optional(),
    }).optional(),
    medicalBills: z.object({
      hasDebts: z.enum(['yes', 'no']).optional(),
      totalBalance: z.number().nonnegative().optional(),
    }).optional(),
    studentLoans: z.object({
      hasLoans: z.enum(['yes', 'no']).optional(),
      totalBalance: z.number().nonnegative().optional(),
      totalMonthlyPayment: z.number().nonnegative().optional(),
    }).optional(),
    hasPersonalLoans: z.enum(['yes', 'no']).optional(),
    personalLoans: z.array(z.object({
      loanType: z.enum(['personal_loan', 'line_of_credit', 'heloc', 'business_loan_pg', 'private_individual_loan']).optional(),
      lenderName: z.string().optional(),
      originalBalance: z.number().nonnegative().optional(),
      currentBalance: z.number().nonnegative().optional(),
      monthlyPayment: z.number().nonnegative().optional(),
      isSecured: z.enum(['yes', 'no']).optional(),
      collateralType: z.enum(['real_estate', 'vehicle', 'investment_account', 'business_assets', 'personal_property', 'other']).optional(),
      collateralDescription: z.string().optional(),
    })).optional(),
    hasTaxesOwed: z.enum(['yes', 'no']).optional(),
    taxesOwed: z.array(z.object({
      authority: z.string().optional(),
      originalBalance: z.number().nonnegative().optional(),
      balanceOwed: z.number().nonnegative().optional(),
      monthlyPayment: z.number().nonnegative().optional(),
    })).optional(),
    hasOtherObligations: z.enum(['yes', 'no']).optional(),
    otherObligations: z.array(z.object({
      description: z.string().optional(),
      amountOwed: z.number().nonnegative().optional(),
      monthlyPayment: z.number().nonnegative().optional(),
    })).optional(),
  }).optional(),
  contingentLiabilities: z.object({
    asEndorserOrCoMaker: z.object({
      hasExposure: z.enum(['yes', 'no']).optional(),
      estimatedAmount: z.number().nonnegative().optional(),
    }).optional(),
    legalClaimsAndJudgments: z.object({
      hasExposure: z.enum(['yes', 'no']).optional(),
      estimatedAmount: z.number().nonnegative().optional(),
    }).optional(),
    provisionForFederalIncomeTax: z.object({
      hasExposure: z.enum(['yes', 'no']).optional(),
      estimatedAmount: z.number().nonnegative().optional(),
    }).optional(),
    otherSpecialDebt: z.object({
      hasExposure: z.enum(['yes', 'no']).optional(),
      estimatedAmount: z.number().nonnegative().optional(),
    }).optional(),
  }).optional(),
  incomeDetails: z.object({
    employmentIncome: z.object({
      hasIncome: z.enum(['yes', 'no']).optional(),
      averageGrossMonthlyIncome: z.number().nonnegative().optional(),
    }).optional(),
    rentalIncome: z.object({
      hasIncome: z.enum(['yes', 'no']).optional(),
      averageNetMonthlyIncome: z.number().nonnegative().optional(),
    }).optional(),
    investmentIncome: z.object({
      hasIncome: z.enum(['yes', 'no']).optional(),
      averageNetMonthlyIncome: z.number().nonnegative().optional(),
    }).optional(),
    otherIncome: z.object({
      hasIncome: z.enum(['yes', 'no']).optional(),
      averageMonthlyIncome: z.number().nonnegative().optional(),
      description: z.string().optional(),
      sources: z.array(z.object({
        sourceType: z.string().optional(),
        description: z.string().optional(),
        averageMonthlyAmount: z.number().nonnegative().optional(),
      })).optional(),
    }).optional(),
  }).optional(),
  annualIncome: z.object({
    salary: z.number().nonnegative().optional(),
    netInvestmentIncome: z.number().optional(),
    realEstateIncome: z.number().optional(),
    otherIncome: z.number().optional(),
    incomeContingencies: z.string().optional(),
  }).optional(),
  realEstateOwned: z.array(z.object({
    propertyType: z.enum(['primary_residence', 'rental_property', 'second_home', 'land', 'commercial_property', 'other']).optional(),
    propertyAddress: z.string().optional(),
    datePurchased: z.string().optional(),
    originalCost: z.number().optional(),
    presentMarketValue: z.number().optional(),
    mortgageHolderName: z.string().optional(),
    mortgageHolderAddress: z.string().optional(),
    mortgageAccountNumber: z.string().optional(),
    mortgageBalance: z.number().optional(),
    amountOfPaymentPerMonth: z.number().optional(),
    status: z.string().optional(),
  })).optional(),
  stocksAndBonds: z.array(z.object({
    symbol: z.string().optional(),
    issuerName: z.string().optional(),
    numberOfShares: z.number().optional(),
    cost: z.number().optional(),
    marketValue: z.number().optional(),
    dateOfQuote: z.string().optional(),
    exchange: z.string().optional(),
  })).optional(),
  otherPersonalPropertyAndOtherAssets: z.array(z.object({
    description: z.string().optional(),
    value: z.number().optional(),
  })).optional(),
  retirementAccounts: z.array(z.object({
    accountType: z.enum(['traditional_ira', 'roth_ira', '401k', 'sep_ira', 'simple_ira', 'solo_401k', 'other']).optional(),
    institutionName: z.string().optional(),
    currentEstimatedValue: z.number().optional(),
    pledgedAsCollateral: z.enum(['yes', 'no']).optional(),
    lenderName: z.string().optional(),
    lienAmount: z.number().optional(),
    monthlyPayment: z.number().optional(),
  })).optional(),
  vehiclesOwned: z.array(z.object({
    year: z.number().int().min(1886).max(2100).optional(),
    make: z.string().max(80).optional(),
    model: z.string().max(80).optional(),
    description: z.string().optional(),
    currentEstimatedValue: z.number().optional(),
    loanBalance: z.number().optional(),
    monthlyPayment: z.number().optional(),
  })).optional(),
  accountsAndNotesReceivable: z.array(z.object({
    debtorName: z.string().optional(),
    originalAmountLoaned: z.number().optional(),
    currentBalanceOwed: z.number().optional(),
    monthlyPaymentReceived: z.number().optional(),
    hasWrittenAgreement: z.enum(['yes', 'no']).optional(),
    isSecuredByCollateral: z.enum(['yes', 'no']).optional(),
    collateralDescription: z.string().optional(),
  })).optional(),
  notesPayableToBanksAndOthers: z.array(z.object({
    nameAndAddressOfNoteholder: z.string().optional(),
    originalBalance: z.number().optional(),
    currentBalance: z.number().optional(),
    paymentAmount: z.number().optional(),
    frequency: z.string().optional(),
    howSecuredOrEndorsed: z.string().optional(),
  })).optional(),
  lifeInsuranceHeld: z.array(z.object({
    companyName: z.string().optional(),
    policyType: z.enum(['whole_life', 'universal_life', 'variable_life', 'indexed_universal_life', 'other_permanent', 'not_sure']).optional(),
    faceAmount: z.number().optional(),
    cashSurrenderValue: z.number().optional(),
    beneficiaries: z.string().optional(),
    pledgedAsCollateral: z.enum(['yes', 'no']).optional(),
    lenderName: z.string().optional(),
    loanAgainstPolicy: z.number().optional(),
  })).optional(),
  sba413Page3Entries: z.array(z.object({
    section: z.string().optional(),
    description: z.string().optional(),
    amount: z.number().optional(),
  })).optional(),
  eSignature: z.object({
    fullName: z.string().optional(),
    signedAt: z.string().optional(),
    attested: z.boolean().optional(),
  }).optional(),
  notes: z.string().optional(),
});

export const PersonalDebtSummarySchema = z.object({
  asOfDate: z.string().min(1, "As of date is required"),
  personalInfo: z.object({
    name: z.string().min(1, "Name is required"),
  }),
  debts: z.array(z.object({
    category: z.enum(['credit_cards', 'line_of_credit', 'real_estate', 'student_debt', 'vehicle', 'other_debt']).optional(),
    creditor: z.string().min(1, "Creditor name is required"),
    accountNumber: z.string().optional(),
    originalAmount: z.number().nonnegative("Original amount must be non-negative"),
    currentBalance: z.number().nonnegative("Current balance must be non-negative"),
    monthlyPayment: z.number().nonnegative("Monthly payment must be non-negative"),
    creditLimit: z.number().nonnegative("Credit limit must be non-negative").optional(),
    interestRate: z.number().min(0).max(100).optional(),
    maturityDate: z.string().optional(),
    collateral: z.string().optional(),
  })),
  notes: z.string().optional(),
});

export const BusinessDebtSummarySchema = z.object({
  asOfDate: z.string().min(1, "As of date is required"),
  businessInfo: z.object({
    name: z.string().min(1, "Business name is required"),
    ein: z.string().optional(),
    address: z.string().optional(),
  }),
  debts: z.array(z.object({
    category: z.enum(['credit_cards', 'line_of_credit', 'real_estate', 'term_loans', 'vehicle_equipment', 'other_debt']).optional(),
    creditor: z.string().min(1, "Creditor name is required"),
    accountNumber: z.string().optional(),
    originalAmount: z.number().nonnegative("Original amount must be non-negative"),
    currentBalance: z.number().nonnegative("Current balance must be non-negative"),
    monthlyPayment: z.number().nonnegative("Monthly payment must be non-negative"),
    creditLimit: z.number().nonnegative("Credit limit must be non-negative").optional(),
    interestRate: z.number().min(0).max(100).optional(),
    maturityDate: z.string().optional(),
    collateral: z.string().optional(),
    personalGuarantee: z.boolean().optional(),
  })),
  notes: z.string().optional(),
});

export const TemplateSchemaMap = {
  balance_sheet: BalanceSheetSchema,
  income_statement: IncomeStatementSchema,
  personal_financial_statement: PersonalFinancialStatementSchema,
  personal_debt_summary: PersonalDebtSummarySchema,
  business_debt_summary: BusinessDebtSummarySchema,
} as const;
